# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='static/imgs/default.png', upload_to='avatar/'),
        ),
    ]
