# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0002_auto_20180815_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='down_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='up_num',
            field=models.IntegerField(default=0),
        ),
    ]
