# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0003_auto_20180815_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='comment_num',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='down_num',
            new_name='down_count',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='up_num',
            new_name='up_count',
        ),
    ]
